version: '3.8'

x-environment: &environment
  PYTHONOPTIMIZE: "1"
  MONGO_URL: mongodb://mongos:27018/swag?appname=swag&readPreference=secondaryPreferred&connect=false&connectTimeoutMS=1000&compressors=zstd
  CELERY_BROKER_WRITE_URL: redis://broker-master:6380/0
  CELERY_BROKER_READ_URL: redis://broker-slave:6381/0
  CELERY_RESULT_BACKEND: redis://results:6382/0
  CELERY_TRACE_APP: "1"
  CACHE_REDIS_URL: redis://cache:6379/0?max_connections=20&timeout=5
  RATELIMIT_STORAGE_URL: redis://cache:6379/3?max_connections=1&timeout=5
  INTERNAL_SERVER_NAME: swag-api.default.svc.cluster.local
  PUSHER_CHANNELS_API_ENDPOINT: http://pusher:3000
  MONGODB_EVENT_LISTENERS: swag.utils.loggers.CommandLogger

networks:
  default:
    driver: bridge
# volumes:
#   postgres:
services:
  # frontend:
  #   image: openresty/openresty:alpine
  #   volumes:
  #   - ./config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
  #   - ./staticfiles:/usr/share/nginx/html:ro
  #   environment:
  #     VERSION: HEAD
  #   ports:
  #   - "8000:80"
  #   depends_on:
  #   - web
  #   networks:
  #   - default
  web:
    command: uvicorn main:app --reload --host 0.0.0.0
    build:
      context: .
    env_file: .env
    environment:
      << : *environment
      PYTHONWARNINGS: default
    volumes:
    - .:/usr/src/app/
    ports:
    - "8000:8000"
    networks:
    - default
  # postgres:
  #   image: postgres
  #   ports:
  #   - "5432:5432"
  #   volumes:
  #     - postgres:/data/db
  #   environment:
  #     POSTGRES_USER: example
  #     POSTGRES_PASSWORD: example
  #     POSTGRES_DB: example
  #   networks:
  #     - default
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
