name: Docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Setup
    #   id: config
    #   run: |
    #     NPROC=$(nproc)
    #     echo "NPROC=$NPROC" >> $GITHUB_ENV
    #     echo "::set-output name=NPROC::$NPROC"
    #     [[ $GITHUB_REF =~ ^refs\/(tags\/|heads\/(master|release|hotfix)$) ]] && echo "::set-output name=push-to-registry::true" || true
    # - name: Setup - buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Setup - Google Artifact Registry
    #   uses: docker/login-action@v1
    #   if: ${{ steps.config.outputs.push-to-registry }}
    #   with:
    #     registry: asia-docker.pkg.dev
    #     username: _json_key
    #     password: ${{ secrets.GOOGLE_SA_GCR_JSON }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v1
      # if: ${{ steps.config.outputs.push-to-registry }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=sha
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        # build-args: |
        #   MAKEFLAGS=-j${{ env.NPROC }}
        cache-from: type=gha
        cache-to: type=gha,mode=max